filebeat.inputs:
  - type: container
    paths:
      - "/var/lib/docker/containers/*/*.log"

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "app-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - equals:
            container.name: app
    # - index: "registry-%{[agent.version]}-%{+yyyy.MM.dd}"
    #   when.or:
    #     - equals:
    #         container.name: registry
    # - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
logging.json: true
logging.metrics.enabled: false
